version: '3.9'
services:
  redis:
    container_name: nestapp-redis
    image: 'redis'
    ports:
      - '6379:6379'
  client:
    container_name: websocket-client
    image: websocket-client
    restart: on-failure
    build: 
      context: websocket-client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
  grpc:
    container_name: grpc
    image: grpc
    restart: on-failure
    build: 
      dockerfile: Dockerfile.grpc
    ports:
      - '50051:50051'
  nestapp:
    container_name: nestapp
    image: nestapp
    restart: on-failure
    build: 
      dockerfile: Dockerfile.server
    depends_on:
      - redis
    ports:
      - '8000:8000'
 