// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: grpc/solver.proto

package solver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SolverService_SolveNonce_FullMethodName = "/solver.SolverService/SolveNonce"
)

// SolverServiceClient is the client API for SolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolverServiceClient interface {
	SolveNonce(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error)
}

type solverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSolverServiceClient(cc grpc.ClientConnInterface) SolverServiceClient {
	return &solverServiceClient{cc}
}

func (c *solverServiceClient) SolveNonce(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, SolverService_SolveNonce_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolverServiceServer is the server API for SolverService service.
// All implementations must embed UnimplementedSolverServiceServer
// for forward compatibility
type SolverServiceServer interface {
	SolveNonce(context.Context, *Message) (*Response, error)
	mustEmbedUnimplementedSolverServiceServer()
}

// UnimplementedSolverServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSolverServiceServer struct {
}

func (UnimplementedSolverServiceServer) SolveNonce(context.Context, *Message) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolveNonce not implemented")
}
func (UnimplementedSolverServiceServer) mustEmbedUnimplementedSolverServiceServer() {}

// UnsafeSolverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolverServiceServer will
// result in compilation errors.
type UnsafeSolverServiceServer interface {
	mustEmbedUnimplementedSolverServiceServer()
}

func RegisterSolverServiceServer(s grpc.ServiceRegistrar, srv SolverServiceServer) {
	s.RegisterService(&SolverService_ServiceDesc, srv)
}

func _SolverService_SolveNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServiceServer).SolveNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolverService_SolveNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServiceServer).SolveNonce(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// SolverService_ServiceDesc is the grpc.ServiceDesc for SolverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solver.SolverService",
	HandlerType: (*SolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolveNonce",
			Handler:    _SolverService_SolveNonce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/solver.proto",
}
